spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stelliocode}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_KEY:secret}