spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stelliocode}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret: ${JWT_KEY:secret}
app:
  cors:
    allowed-origin: ${ORIGIN}
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}
stripe:
  api-key: ${STRIPE_API_KEY}